sample_prompts:
  filter_length: false
  name: no_lengthfilter-bm25_doc_level_onthefly
  nprompts: 5
  onthefly: true
  per_p_budget: 20
  sample_on_new: true
  sampling_method: bm25_doc_level
  shuffle_mode: None
