sample_prompts:
  filter_length: false
  name: no_lengthfilter-nn_doc_level_windowb_onthefly
  nprompts: 5
  onthefly: true
  per_p_budget: 0
  sample_on_new: true
  sampling_method: nn_doc_level
  shuffle_mode: None
