sample_prompts:
  bankname: lengthfilter-random
  filter_length: true
  name: lengthfilter-doc_level_gen
  nprompts: 5
  sample_on_new: true
  sampling_method: doc_level
  shuffle_mode: None
  test_use_gold: false
  train_use_gold: true
