sample_prompts:
  do_submodopt: true
  filter_length: false
  name: no_lengthfilter-bm25-submodopt_nob
  nprompts: 5
  per_p_budget: -1
  sample_on_new: true
  sampling_method: bm25
  shuffle_mode: None
